interface ImageInfo {
  url: string;
  width: number;
  height: number;
}

interface Category {
  id: number;
  parentId?: number;
  orderBy: number;
  hdThumbnailUrl: string;
  thumbnailUrl: string;
  originalImageUrl: string;
  imageUrl: string;
  originalImage: ImageInfo;
  thumbnail: ImageInfo;
  borderInfo: {
    dominatingColor: {
      red: number;
      green: number;
      blue: number;
      alpha: number;
    };
    homogeneity: boolean;
  };
  name: string;
  nameTranslated: {
    [language: string]: string;
  };
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  description: string;
  descriptionTranslated: {
    [language: string]: string;
  };
  enabled: boolean;
  isSampleCategory: boolean;
  seoTitle: string;
  seoDescription: string;
  alt: {
    [key: string]: string;
  };
}

interface CategoryListResponse {
  total: number;
  count: number;
  offset: number;
  limit: number;
  items: Category[];
}
