<template>
  <section class="product_info">
    <div v-if="!isLoading && product" class="product_info_card">
      <img
        class="product_info_image"
        :src="product?.imageUrl"
        :alt="product?.autogeneratedSlug"
      />
      <section class="right_card_section">
        <div class="product_info_main_info">
          <h3>{{ product?.name }}</h3>
          <h4>Price: {{ product?.price }}</h4>
        </div>
        <article
          class="product_info_description"
          v-html="product?.description"
        ></article>
        <div class="product_info_button_group">
          <CartButtonGroup :id="product?.id" />
        </div>
      </section>
    </div>
    <span v-else>Loading...</span>
  </section>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { type IProduct } from "@/api/products/productsTypes";
import { useRoute } from "vue-router";
import { getProduct } from "@/api/products/products";
import useLoading from "@/hooks/useLoading";
import CartButtonGroup from "@/components/modules/CartButtonGroup.vue";

const { isLoading, setIsLoading } = useLoading;
const product = ref<IProduct | null>(null);
const { params } = useRoute();
onMounted(async () => {
  setIsLoading(true);
  product.value = await getProduct(params.prod_id as string);
  setIsLoading(false);
});
</script>

<style lang="scss" scoped>
.product_info {
  display: flex;
  width: 100%;
  justify-content: center;
  align-items: center;
  gap: 40px;
}

.product_info_card {
  width: 60%;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  border: 1px rgb(230, 230, 230) solid;
  padding: 24px;
  border-radius: 12px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  gap: 40px;
}

.right_card_section {
  display: flex;
  flex-direction: column;
  align-items: start;
  justify-content: start;
  height: 100%;
  gap: 30px;
}

.product_info_main_info {
  display: flex;
  flex-direction: column;
  gap: 40px;
}

.product_info_image {
  width: 60%;
  border-radius: 12px;
}

.product_info_description {
  width: 300px;
}

.product_info_button_group {
  width: 100%;
}

@media only screen and (max-width: 1350px) {
  .product_info_card {
    flex-direction: column;
  }
}

@media only screen and (max-width: 550px) {
  .product_info_card {
    flex-direction: column;
  }
  .product_info_description {
    max-width: 200px;
  }
}
</style>
